SET(PACKAGE_VERSION "11.0.3")
SET(PACKAGE_VERSION_MAJOR "11")

IF(${PACKAGE_FIND_VERSION_MAJOR} EQUAL ${PACKAGE_VERSION_MAJOR})
  SET(PACKAGE_VERSION_COMPATIBLE 1)
  IF(${PACKAGE_FIND_VERSION} VERSION_EQUAL ${PACKAGE_VERSION})
    SET(PACKAGE_VERSION_EXACT 1)
  ENDIF()
ENDIF()
